DATABASE_VINILI = [
    {
        "id": 1,
        "artista": "Pink Floyd",
        "titolo_album": "The Dark Side of the Moon",
        "genere": "Progressive Rock",
        "anno_uscita_originale": 1973,
        "anno_stampa": 1983,
        "anno_uscita_stampa":1984,
        "origine": "IT",
        "etichetta": "Harvest (distribuita in Italia da EMI)",
        "catalog_number": "STEREO 3C06405249",
        "codice_matrice": "05249",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "120-125g",
        "inserti": "1 Poster",
        "stato_disco": "8",
        "stato_copertina": "5",
        "note_stato": "",
        "stato_catalogo": "Personale",
        "cover": "Img/The_Dark_Side_Of_The_Moon.jpg",
        "tracce": [
            {"pos": "A1", "title": "Speak to Me", "duration": "1:30"},
            {"pos": "A2", "title": "Breathe (In the Air)", "duration": "2:43"},
            {"pos": "A3", "title": "On the Run", "duration": "3:36"},
            {"pos": "A4", "title": "Time", "duration": "6:53"},
            {"pos": "A5", "title": "The Great Gig in the Sky", "duration": "4:36"},
            {"pos": "B1", "title": "Money", "duration": "6:22"},
            {"pos": "B2", "title": "Us and Them", "duration": "7:46"},
            {"pos": "B3", "title": "Any Colour You Like", "duration": "3:25"},
            {"pos": "B4", "title": "Brain Damage", "duration": "3:48"},
            {"pos": "B5", "title": "Eclipse", "duration": "2:03"}
        ],
        "foto_album": [
        "Img/The_Dark_Side_Of_The_Moon_Foto/Fronte.jpg",
        "Img/The_Dark_Side_Of_The_Moon_Foto/Retro.jpg",
        "Img/The_Dark_Side_Of_The_Moon_Foto/Interno.jpg",
        "Img/The_Dark_Side_Of_The_Moon_Foto/Side_1.jpg",
        "Img/The_Dark_Side_Of_The_Moon_Foto/Side_2.jpg"
    ]
    },
    {
        "id": 2,
        "artista": "Pink Floyd",
        "titolo_album": "Wish You Were Here",
        "genere": "Progressive Rock",
        "anno_uscita_originale": 1975,
        "anno_stampa": 2016,
        "anno_uscita_stampa":2016,
        "origine": "EU (BIEM/GEMA)",
        "etichetta": "Columbia / Pink Floyd Music Ltd.",
        "catalog_number": "STEREO 88875184261 B",
        "codice_matrice": "18958 6A - 5B",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "180g",
        "inserti": "1 Cartolina",
        "stato_disco": "10",
        "stato_copertina": "10",
        "note_stato": "",
        "stato_catalogo": "Personale",
        "cover": "Img/Wish_You_Were_Here.jpg",
        "tracce": [
            {"pos": "A1", "title": "Shine On You Crazy Diamond (Parts 1-5)", "duration": "13:32"},
            {"pos": "A2", "title": "Welcome to the Machine", "duration": "7:31"},
            {"pos": "B1", "title": "Have a Cigar", "duration": "5:08"},
            {"pos": "B2", "title": "Wish You Were Here", "duration": "5:34"},
            {"pos": "B3", "title": "Shine On You Crazy Diamond (Parts 6-9)", "duration": "12:31"}
            ]
        ,
        "foto_album": [
        "Img/Wish_You_Were_Here_Foto/Fronte.jpg",
        "Img/Wish_You_Were_Here_Foto/Retro.jpg",
        "Img/Wish_You_Were_Here_Foto/Tracce.jpg",
        "Img/Wish_You_Were_Here_Foto/Side_1.jpg",
        "Img/Wish_You_Were_Here_Foto/Side_2.jpg"
    ]
    },
    {
        "id": 3,
        "artista": "King Crimson",
        "titolo_album": "Discipline",
        "genere": "New Wave / Progressive Rock",
        "anno_uscita_originale": 1981,
        "anno_stampa": 1983,
        "anno_uscita_stampa": 1983,
        "origine": "USA (Winchester Pressing)",
        "etichetta": "Warner Bros. Records / EG",
        "catalog_number": "BSK 3629",
        "codice_matrice": "BSK-2-3629-E-1 ─◁ EDP",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "120g",
        "inserti": "Nessuno",
        "stato_disco": "Da Valutare",
        "stato_copertina": "5",
        "note_stato": "",
        "stato_catalogo": "Personale",
        "cover": "Img/Discipline.jpg",
        "tracce": [
            {"pos": "A1", "title": "Elephant Talk", "duration": "4:43"},
            {"pos": "A2", "title": "Frame by Frame", "duration": "5:09"},
            {"pos": "A3", "title": "Matte Kudasai", "duration": "3:47"},
            {"pos": "A4", "title": "Indiscipline", "duration": "4:33"},
            {"pos": "B1", "title": "Thela Hun Ginjeet", "duration": "6:26"},
            {"pos": "B2", "title": "The Sheltering Sky", "duration": "8:22"},
            {"pos": "B3", "title": "Discipline", "duration": "5:13"}
        ],
        "foto_album": [
            "Img/Discipline_Foto/Label_Side_B.jpg",
            "Img/Discipline_Foto/Matrix_Detail.jpg"
        ]
    },
    {
    "id": 4,
    "artista": "Mayhem",
    "titolo_album": "Daemon",
    "genere": "Black Metal",
    "anno_uscita_originale": 2019,
    "anno_stampa": 2022,
    "anno_uscita_stampa": 2022,
    "origine": "EU (BIEM/GEMA)",
    "etichetta": "Century Media",
    "catalog_number": "19439989711",
    "codice_matrice": "BK62065-01 A1",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "180g",
    "inserti": "",
    "stato_disco": "10",
    "stato_copertina": "10",
    "note_stato": "Copia in ottime condizioni",
    "stato_catalogo": "Personale",
    "cover": "Img/Daemon.jpg",
    "tracce": [
        {"pos": "A1", "title": "The Dying False King", "duration": "3:45"},
        {"pos": "A2", "title": "Agenda Ignis", "duration": "4:34"},
        {"pos": "A3", "title": "Bad Blood", "duration": "4:58"},
        {"pos": "A4", "title": "Malum", "duration": "5:05"},
        {"pos": "A5", "title": "Falsified and Hated", "duration": "5:48"},
        {"pos": "B1", "title": "Aeon Daemonium", "duration": "6:03"},
        {"pos": "B2", "title": "Worthless Abominations Destroyed", "duration": "3:48"},
        {"pos": "B3", "title": "Daemon Spawn", "duration": "6:02"},
        {"pos": "B4", "title": "Of Worms and Ruins", "duration": "3:48"},
        {"pos": "B5", "title": "Invoke the Oath", "duration": "5:33"}
    ],
    "foto_album": [
        "Img/Mayhem_Daemon_Foto/Side_A.jpg",
        "Img/Mayhem_Daemon_Foto/Matrix.jpg"
    ]
},

    {
        "id": 5,
        "artista": "Nirvana",
        "titolo_album": "In Utero",
        "genere": "Grunge",
        "anno_uscita_originale": 1993,
        "anno_stampa": 2023,
        "anno_uscita_stampa": 2023,
        "origine": "??",
        "etichetta": "Geffen Records",
        "catalog_number": "060245517858",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "180g",
        "inserti": "5 B-sides & bonus tracks",
        "stato_disco": "10",
        "stato_copertina": "10",
        "note_stato": "30th Anniversary Edition Limited Edition",
        "stato_catalogo": "Personale",
        "cover": "Img/In_Utero.jpg",
        "tracce": [],
        "foto_album": ["Img/In_Utero_Foto/Fronte.jpg"]
    },
    {
        "id": 6,
        "artista": "Motörhead",
        "titolo_album": "Another Perfect Day",
        "genere": "Hard Rock / Heavy Metal",
        "anno_uscita_originale": 1983,
        "anno_stampa": "??",
        "anno_uscita_stampa": "??",
        "origine": "??",
        "etichetta": "Bronze",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "8",
        "note_stato": "Copertina integra con lievi segni di usura",
        "stato_catalogo": "Personale",
        "cover": "Img/Another_Perfect_Day.jpg",
        "tracce": [],
        "foto_album": ["Img/Another_Perfect_Day_Foto/Fronte.jpg"]
    },
    {
        "id": 7,
        "artista": "Pink Floyd",
        "titolo_album": "The Wall",
        "genere": "Progressive Rock",
        "anno_uscita_originale": 1979,
        "anno_stampa": "??",
        "anno_uscita_stampa": "??",
        "origine": "??",
        "etichetta": "Harvest / Columbia",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "9",
        "note_stato": "Copertina pulita",
        "stato_catalogo": "Personale",
        "cover": "Img/The_Wall.jpg",
        "tracce": [],
        "foto_album": ["Img/The_Wall_Foto/Fronte.jpg"]
    },
    {
        "id": 8,
        "artista": "Arctic Monkeys",
        "titolo_album": "AM",
        "genere": "Indie Rock",
        "anno_uscita_originale": 2013,
        "anno_stampa": "??",
        "anno_uscita_stampa": "??",
        "origine": "??",
        "etichetta": "Domino",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "10",
        "note_stato": "",
        "stato_catalogo": "Personale",
        "cover": "Img/Am.jpg",
        "tracce": [],
        "foto_album": ["Img/AM_Foto/Fronte.jpg"]
    },
    {
        "id": 9,
        "artista": "Salmo",
        "titolo_album": "Death USB",
        "genere": "Rap / Hardcore Hip Hop",
        "anno_uscita_originale": 2012,
        "anno_stampa": "??",
        "anno_uscita_stampa": "??",
        "origine": "Italy",
        "etichetta": "Tanta Roba Label",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "Nero",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "10",
        "note_stato": "Ancora nel cellophan",
        "stato_catalogo": "Personale",
        "cover": "Img/Death_USB.jpg",
        "tracce": [],
        "foto_album": ["Img/Death_USB_Foto/Fronte.jpg"]
    },
    {
        "id": 10,
        "artista": "Daniel Pemberton",
        "titolo_album": "Spider-Man: Across the Spider-Verse (Original Score)",
        "genere": "Soundtrack / Score",
        "anno_uscita_originale": 2023,
        "anno_stampa": 2023,
        "anno_uscita_stampa": 2023,
        "origine": "??",
        "etichetta": "Sony Classical",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "??",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "10",
        "note_stato": "Copia nuova",
        "stato_catalogo": "Personale",
        "cover": "Img/Spiderman_Across_The_Spiderverse.jpg",
        "tracce": [],
        "foto_album": ["Img/SpiderVerse_Foto/Fronte.jpg"]
    },
    {
        "id": 12,
        "artista": "Noyz Narcos",
        "titolo_album": "Virus",
        "genere": "Rap",
        "anno_uscita_originale": 2022,
        "anno_stampa": 2022,
        "anno_uscita_stampa": 2022,
        "origine": "Italy",
        "etichetta": "Thaurus / Sony Music",
        "catalog_number": "??",
        "codice_matrice": "??",
        "velocita": "33",
        "colore": "??",
        "grammatura": "??",
        "inserti": "??",
        "stato_disco": "??",
        "stato_copertina": "10",
        "note_stato": "",
        "stato_catalogo": "Personale",
        "cover": "Img/Virus.webp",
        "tracce": [],
        "foto_album": ["Img/Virus_Foto/Fronte.jpg"]
    },
    {
    "id": 13,
    "artista": "Night Skinny",
    "titolo_album": "Botox",
    "genere": "Hip Hop / Trap",
    "anno_uscita_originale": 2022,
    "anno_stampa": 2022,
    "anno_uscita_stampa": 2022,
    "origine": "Italy",
    "etichetta": "Columbia / Sony Music",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "10",
    "note_stato": "Copertina con artwork bistecca",
    "stato_catalogo": "Personale",
    "cover": "Img/Botox.jpg",
    "tracce": [
        {"pos": "A1", "title": "Fake", "duration": "??"},
        {"pos": "A2", "title": "Diavolo", "duration": "??"},
        {"pos": "A3", "title": "Blessed", "duration": "??"},
        {"pos": "A4", "title": "Marciapiede", "duration": "??"},
        {"pos": "A5", "title": "Addio", "duration": "??"},
        {"pos": "B1", "title": "Scalpello", "duration": "??"},
        {"pos": "B2", "title": "Così non va", "duration": "??"},
        {"pos": "B3", "title": "Marmellata", "duration": "??"},
        {"pos": "B4", "title": "Changes", "duration": "???"}
    ],
    "foto_album": ["Img/Botox_Foto/Fronte.jpg"]
},
  {
    "id": 14,
    "artista": "Pink Floyd",
    "titolo_album": "The Dark Side of the Moon",
    "genere": "Progressive Rock",
    "anno_uscita_originale": 1973,
    "anno_stampa": 1983,
    "anno_uscita_stampa": 1984,
    "origine": "IT",
    "etichetta": "Harvest (distribuita in Italia da EMI)",
    "catalog_number": "STEREO 3C06405249",
    "codice_matrice": "05249",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "120-125g",
    "inserti": "1 Poster",
    "stato_disco": "8",
    "stato_copertina": "5",
    "note_stato": "",
    "stato_catalogo": "Eredità",
    "cover": "Img/The_Dark_Side_Of_The_Moon.jpg",
    "tracce": [
      {"pos": "A1", "title": "Speak to Me", "duration": "1:30"},
      {"pos": "A2", "title": "Breathe (In the Air)", "duration": "2:43"},
      {"pos": "A3", "title": "On the Run", "duration": "3:36"},
      {"pos": "A4", "title": "Time", "duration": "6:53"},
      {"pos": "A5", "title": "The Great Gig in the Sky", "duration": "4:36"},
      {"pos": "B1", "title": "Money", "duration": "6:22"},
      {"pos": "B2", "title": "Us and Them", "duration": "7:46"},
      {"pos": "B3", "title": "Any Colour You Like", "duration": "3:25"},
      {"pos": "B4", "title": "Brain Damage", "duration": "3:48"},
      {"pos": "B5", "title": "Eclipse", "duration": "2:03"}
    ],
    "foto_album": ["Img/The_Dark_Side_Of_The_Moon_Foto/Fronte.jpg", "Img/The_Dark_Side_Of_The_Moon_Foto/Retro.jpg"]
  },
  {
    "id": 15,
    "artista": "Uriah Heep",
    "titolo_album": "Abominog Expanded Version",
    "genere": "Hard Rock",
    "anno_uscita_originale": 1982,
    "anno_stampa": 1982,
    "anno_uscita_stampa": 1982,
    "origine": "??",
    "etichetta": "Bronze",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Personale",
    "cover": "Img/Abominog_Expanded_Version.jpg",
    "tracce": [
      {"pos": "A1", "title": "Too Scared to Run", "duration": "3:49"},
      {"pos": "A2", "title": "Chasing Shadows", "duration": "4:39"},
      {"pos": "A3", "title": "On the Rebound", "duration": "3:14"},
      {"pos": "A4", "title": "Hot Night in a Cold Town", "duration": "4:03"},
      {"pos": "A5", "title": "Running All Night (with the Lion)", "duration": "4:28"},
      {"pos": "B1", "title": "That's the Way That It Is", "duration": "4:06"},
      {"pos": "B2", "title": "Prisoner", "duration": "4:27"},
      {"pos": "B3", "title": "Hot Persuasion", "duration": "3:48"},
      {"pos": "B4", "title": "Sell Your Soul", "duration": "5:25"},
      {"pos": "B5", "title": "Think It Over", "duration": "3:42"}
    ],
    "foto_album": ["Img/Abominog_Foto/Fronte.jpg"]
  },
  {
    "id": 16,
    "artista": "Pink Floyd",
    "titolo_album": "Animals",
    "genere": "Progressive Rock",
    "anno_uscita_originale": 1977,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Personale",
    "cover": "Img/Animals.jpg",
    "tracce": [
      {"pos": "A1", "title": "Pigs on the Wing 1", "duration": "1:25"},
      {"pos": "A2", "title": "Dogs", "duration": "17:03"},
      {"pos": "B1", "title": "Sheep", "duration": "10:18"},
      {"pos": "B2", "title": "Pigs (Three Different Ones)", "duration": "11:25"},
      {"pos": "B3", "title": "Pigs on the Wing 2", "duration": "1:23"}
    ],
    "foto_album": ["Img/Animals_Foto/Fronte.jpg"]
  },
  {
    "id": 18,
    "artista": "Testament",
    "titolo_album": "Dark Roots of Earth",
    "genere": "Thrash Metal",
    "anno_uscita_originale": 2012,
    "anno_stampa": 2012,
    "anno_uscita_stampa": 2012,
    "origine": "??",
    "etichetta": "Nuclear Blast",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Vinyl Splatter (Gold/Green)",
    "grammatura": "??",
    "inserti": "Limited Edition",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "Sigillato",
    "stato_catalogo": "Personale",
    "cover": "Img/Dark_Roots_Of_Earth.jpg",
    "tracce": [
      {"pos": "A1", "title": "Rise Up", "duration": "4:18"},
      {"pos": "A2", "title": "Native Blood", "duration": "5:21"},
      {"pos": "A3", "title": "Dark Roots of Earth", "duration": "5:45"},
      {"pos": "B1", "title": "True American Hate", "duration": "5:22"},
      {"pos": "B2", "title": "A Day in the Death", "duration": "5:38"},
      {"pos": "B3", "title": "Cold Embrace", "duration": "7:45"},
      {"pos": "C1", "title": "Man Kills Mankind", "duration": "5:05"},
      {"pos": "C2", "title": "Throne of Thorns", "duration": "7:04"},
      {"pos": "D1", "title": "Last Stand for Independence", "duration": "4:42"}
    ],
    "foto_album": ["Img/Dark_Roots_Of_Earth_Foto/Fronte.jpg"]
  },
  {
    "id": 19,
    "artista": "AC/DC",
    "titolo_album": "Live on Air 1974-79 (Hell's Highway)",
    "genere": "Hard Rock",
    "anno_uscita_originale": 2016,
    "anno_stampa": 2016,
    "anno_uscita_stampa": 2016,
    "origine": "EU",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Flaming Orange",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "Prezzo etichetta 26,00€",
    "stato_catalogo": "Personale",
    "cover": "Img/Live_On_Air_1974-79.jpg",
    "tracce": [],
    "foto_album": ["Img/Hells_Highway_Foto/Fronte.jpg"]
  },
  {
    "id": 20,
    "artista": "Iron Maiden",
    "titolo_album": "Iron Maiden",
    "genere": "Heavy Metal",
    "anno_uscita_originale": 1980,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Personale",
    "cover": "Img/Iron_Maiden.webp",
    "tracce": [
      {"pos": "A1", "title": "Prowler", "duration": "3:55"},
      {"pos": "A2", "title": "Remember Tomorrow", "duration": "5:27"},
      {"pos": "A3", "title": "Running Free", "duration": "3:17"},
      {"pos": "A4", "title": "Phantom of the Opera", "duration": "7:08"},
      {"pos": "B1", "title": "Transylvania", "duration": "4:19"},
      {"pos": "B2", "title": "Strange World", "duration": "5:45"},
      {"pos": "B3", "title": "Charlotte the Harlot", "duration": "4:12"},
      {"pos": "B4", "title": "Iron Maiden", "duration": "3:35"}
    ],
    "foto_album": ["Img/Iron_Maiden_Foto/Fronte.jpg"]
  },
  {
    "id": 23,
    "artista": "Gorgoroth",
    "titolo_album": "Nazarene Sickness",
    "genere": "Black Metal",
    "anno_uscita_originale": "??",
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "??",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "Black and White cover art",
    "stato_catalogo": "Personale",
    "cover": "Img/Nazarene_Sickness.jpg",
    "tracce": [],
    "foto_album": ["Img/Nazarene_Sickness_Foto/Fronte.jpg"]
  },

  {
    "id": 21,
    "artista": "Black Sabbath",
    "titolo_album": "Sabbath Bloody Sabbath",
    "genere": "Heavy Metal / Doom Metal",
    "anno_uscita_originale": 1973,
    "anno_stampa": 2015,
    "anno_uscita_stampa": 2015,
    "origine": "EU",
    "etichetta": "Sanctuary Records",
    "catalog_number": "BMGRM051LP",
    "codice_matrice": "BMGRM051LP A/B",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "180g",
    "inserti": "Gatefold",
    "stato_disco": "10",
    "stato_copertina": "10",
    "note_stato": "Prezzo indicato: 35€",
    "stato_catalogo": "Personale",
    "cover": "Img/Sabbath_Bloody_Sabbath.jpg",
    "tracce": [
      {"pos": "A1", "title": "Sabbath Bloody Sabbath", "duration": "5:48"},
      {"pos": "A2", "title": "A National Acrobat", "duration": "6:16"},
      {"pos": "A3", "title": "Fluff", "duration": "4:11"},
      {"pos": "A4", "title": "Sabbra Cadabra", "duration": "5:59"},
      {"pos": "B1", "title": "Killing Yourself to Live", "duration": "5:41"},
      {"pos": "B2", "title": "Who Are You?", "duration": "4:11"},
      {"pos": "B3", "title": "Looking for Today", "duration": "4:59"},
      {"pos": "B4", "title": "Spiral Architect", "duration": "5:29"}
    ],
    "foto_album": ["Img/Sabbath_Bloody_Sabbath_Foto/Fronte.jpg"]
  },
  {
    "id": 24,
    "artista": "Limp Bizkit",
    "titolo_album": "Chocolate Starfish and the Hot Dog Flavored Water",
    "genere": "Nu Metal / Rap Metal",
    "anno_uscita_originale": 2000,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Chocolate_Starfish_And_The_Hot_Dog_Flavored_Water.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 25,
    "artista": "Testament",
    "titolo_album": "Souls of Black",
    "genere": "Thrash Metal",
    "anno_uscita_originale": 1990,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Souls_Of_Black.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 26,
    "artista": "Korn",
    "titolo_album": "Untitled",
    "genere": "Nu Metal",
    "anno_uscita_originale": 2007,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Untitled.webp",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 27,
    "artista": "Testament",
    "titolo_album": "Brotherhood of the Snake",
    "genere": "Thrash Metal",
    "anno_uscita_originale": 2016,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Brotherhood_Of_The_Snake.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 28,
    "artista": "Alice in Chains",
    "titolo_album": "Facelift",
    "genere": "Grunge / Alternative Metal",
    "anno_uscita_originale": 1990,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Personale",
    "cover": "Img/Facelift.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 29,
    "artista": "System of a Down",
    "titolo_album": "Toxicity",
    "genere": "Alternative Metal",
    "anno_uscita_originale": 2001,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Personale",
    "cover": "Img/Toxicity.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 30,
    "artista": "Guns N' Roses",
    "titolo_album": "Use Your Illusion I",
    "genere": "Hard Rock",
    "anno_uscita_originale": 1991,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "Specificare se I o II",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Use_Your_Illusion_I.webp",
    "tracce": [],
    "foto_album": []
  },
    {
    "id": 23,
    "artista": "Guns N' Roses",
    "titolo_album": "Use Your Illusion II",
    "genere": "Hard Rock",
    "anno_uscita_originale": 1991,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "Specificare se I o II",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Use_Your_Illusion_II.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 31,
    "artista": "Guns N' Roses",
    "titolo_album": "Chinese Democracy",
    "genere": "Hard Rock",
    "anno_uscita_originale": 2008,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Chinese_Democracy.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 32,
    "artista": "Slayer",
    "titolo_album": "Repentless",
    "genere": "Thrash Metal",
    "anno_uscita_originale": 2015,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Repentless.webp",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 33,
    "artista": "Limp Bizkit",
    "titolo_album": "Significant Other",
    "genere": "Nu Metal",
    "anno_uscita_originale": 1999,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Significant_Other.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 34,
    "artista": "Tame Impala",
    "titolo_album": "Currents",
    "genere": "Psychedelic Pop / Synth-pop",
    "anno_uscita_originale": 2015,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Currents.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 35,
    "artista": "Iron Maiden",
    "titolo_album": "Fear of the Dark",
    "genere": "Heavy Metal",
    "anno_uscita_originale": 1992,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Fear_Of_The_Dark.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 36,
    "artista": "Def Leppard",
    "titolo_album": "Hysteria",
    "genere": "Hard Rock / Glam Metal",
    "anno_uscita_originale": 1987,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Hysteria.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 37,
    "artista": "Korn",
    "titolo_album": "See You on the Other Side",
    "genere": "Nu Metal",
    "anno_uscita_originale": 2005,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/See_You_On_The_Other_Side.webp",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 38,
    "artista": "Deftones",
    "titolo_album": "Around the Fur",
    "genere": "Nu Metal / Alternative Metal",
    "anno_uscita_originale": 1997,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Around_The_Fur.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 39,
    "artista": "Pantera",
    "titolo_album": "Cowboys from Hell",
    "genere": "Groove Metal",
    "anno_uscita_originale": 1990,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Cowboys_From_Hell.jpeg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 40,
    "artista": "Gojira",
    "titolo_album": "From Mars to Sirius",
    "genere": "Progressive Death Metal",
    "anno_uscita_originale": 2005,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/From_Mars_To_Sirius.webp",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 41,
    "artista": "Alice in Chains",
    "titolo_album": "Jar of Flies",
    "genere": "Grunge / Acoustic Rock",
    "anno_uscita_originale": 1994,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Jar_Of_Flies.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 42,
    "artista": "Slash",
    "titolo_album": "Slash",
    "genere": "Hard Rock",
    "anno_uscita_originale": 2010,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Slash.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 43,
    "artista": "Boston",
    "titolo_album": "Boston",
    "genere": "Hard Rock / AOR",
    "anno_uscita_originale": 1976,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Boston.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 44,
    "artista": "Uriah Heep",
    "titolo_album": "Fallen Angel",
    "genere": "Hard Rock / Progressive Rock",
    "anno_uscita_originale": 1978,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Fallen_Angel.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 45,
    "artista": "Slash",
    "titolo_album": "Apocalyptic Love",
    "genere": "Hard Rock",
    "anno_uscita_originale": 2012,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Apocalyptic_Love.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 46,
    "artista": "Lustra",
    "titolo_album": "Left or Dead",
    "genere": "Pop Punk",
    "anno_uscita_originale": 2006,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Left_Or_Dead.jpeg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 47,
    "artista": "Def Leppard",
    "titolo_album": "Pyromania",
    "genere": "Hard Rock / Glam Metal",
    "anno_uscita_originale": 1983,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Pyromania.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 48,
    "artista": "Judas Priest",
    "titolo_album": "Painkiller",
    "genere": "Heavy Metal",
    "anno_uscita_originale": 1990,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Painkiller.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 49,
    "artista": "Death",
    "titolo_album": "The Sound of Perseverance",
    "genere": "Technical Death Metal",
    "anno_uscita_originale": 1998,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/The_Sound_Of_Perseverance.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 50,
    "artista": "Arch Enemy",
    "titolo_album": "Blood Dynasty",
    "genere": "Melodic Death Metal",
    "anno_uscita_originale": 2025,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Blood_Dynasty.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 51,
    "artista": "Revocation",
    "titolo_album": "Netherheaven",
    "genere": "Technical Death Metal",
    "anno_uscita_originale": 2022,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Netherheaven.jpeg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 52,
    "artista": "Cannibal Corpse",
    "titolo_album": "Torture",
    "genere": "Death Metal",
    "anno_uscita_originale": 2012,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Torture.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 53,
    "artista": "Napalm Death",
    "titolo_album": "Noise for Music's Sake",
    "genere": "Grindcore",
    "anno_uscita_originale": 2003,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Noise_For_Music's_Sake.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 54,
    "artista": "Death Angel",
    "titolo_album": "The Evil Divide",
    "genere": "Thrash Metal",
    "anno_uscita_originale": 2016,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/The_Evil_Divide.jpg",
    "tracce": [],
    "foto_album": []
  },
    {
    "id": 55,
    "artista": "King Crimson",
    "titolo_album": "In the Court of the Crimson King",
    "genere": "Progressive Rock",
    "anno_uscita_originale": 1969,
    "anno_stampa": 2020,
    "anno_uscita_stampa": 2020,
    "origine": "UK/EU",
    "etichetta": "Panegyric",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "200g",
    "inserti": "",
    "stato_disco": "10",
    "stato_copertina": "10",
    "note_stato": "Edizione 50th Anniversary",
    "stato_catalogo": "Personale",
    "cover": "Img/In_The_Court_Of_The_Crimson_King.jpg",
    "tracce": [
      {"pos": "A1", "title": "21st Century Schizoid Man", "duration": "7:21"},
      {"pos": "A2", "title": "I Talk to the Wind", "duration": "6:05"},
      {"pos": "A3", "title": "Epitaph", "duration": "8:47"},
      {"pos": "B1", "title": "Moonchild", "duration": "12:13"},
      {"pos": "B2", "title": "The Court of the Crimson King", "duration": "9:25"}
    ],
    "foto_album": ["Img/Crimson_King_Foto/Fronte.jpg"]
  },
  {
    "id": 56,
    "artista": "Ghost",
    "titolo_album": "Skeletà",
    "genere": "Hard Rock / Heavy Metal",
    "anno_uscita_originale": 2025,
    "anno_stampa": 2025,
    "anno_uscita_stampa": 2025,
    "origine": "SVE/DEN/NOR (Scandinavian Exclusive)",
    "etichetta": "Loma Vista",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Orchid / Magenta",
    "grammatura": "180g",
    "inserti": "Booklet",
    "stato_disco": "10",
    "stato_copertina": "10",
    "note_stato": "Vinile colorato, edizione limitata scandinava",
    "stato_catalogo": "Personale",
    "cover": "Img/Skeleta.webp",
    "tracce": [
      {"pos": "A1", "title": "Imperium", "duration": "1:40"},
      {"pos": "A2", "title": "Kaisarion", "duration": "5:02"},
      {"pos": "A3", "title": "Spillways", "duration": "3:16"},
      {"pos": "A4", "title": "Call Me Little Sunshine", "duration": "4:44"},
      {"pos": "A5", "title": "Hunter's Moon", "duration": "3:16"},
      {"pos": "A6", "title": "Watcher in the Sky", "duration": "4:58"},
      {"pos": "B1", "title": "Dominion", "duration": "1:22"},
      {"pos": "B2", "title": "Twenties", "duration": "3:46"},
      {"pos": "B3", "title": "Darkness at the Heart of My Love", "duration": "4:58"},
      {"pos": "B4", "title": "Griftwood", "duration": "5:16"},
      {"pos": "B5", "title": "Bite of Passage", "duration": "0:31"},
      {"pos": "B6", "title": "Respite on the Spitalfields", "duration": "6:42"}
    ],
    "foto_album": ["Img/Skeleta_Foto/Fronte.jpg"]
  },
  {
    "id": 57,
    "artista": "The Clash",
    "titolo_album": "London Calling",
    "genere": "Punk Rock / Post-Punk",
    "anno_uscita_originale": 1979,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "CBS",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/London_Calling.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 58,
    "artista": "Led Zeppelin",
    "titolo_album": "Led Zeppelin I",
    "genere": "Hard Rock / Blues Rock",
    "anno_uscita_originale": 1969,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Atlantic",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Led_Zeppelin_I.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 59,
    "artista": "Led Zeppelin",
    "titolo_album": "Led Zeppelin II",
    "genere": "Hard Rock / Blues Rock",
    "anno_uscita_originale": 1969,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Atlantic",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Led_Zeppelin_II.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 60,
    "artista": "Led Zeppelin",
    "titolo_album": "Led Zeppelin III",
    "genere": "Hard Rock / Folk Rock",
    "anno_uscita_originale": 1970,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Atlantic",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Led_Zeppelin_III.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 61,
    "artista": "Curren$y",
    "titolo_album": "Pilot Talk Trilogy",
    "genere": "Hip Hop",
    "anno_uscita_originale": 2017,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Empire / Jet Life",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Pilot_Talk_Trilogy.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 62,
    "artista": "The Alan Parsons Project",
    "titolo_album": "Eye in the Sky",
    "genere": "Progressive Rock / Soft Rock",
    "anno_uscita_originale": 1982,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Arista",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Eye_In_The_Sky.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 63,
    "artista": "AC/DC",
    "titolo_album": "Let There Be Rock",
    "genere": "Hard Rock",
    "anno_uscita_originale": 1977,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Albert / Atlantic",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Let_There_Be_Rock.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 64,
    "artista": "Derek and the Dominos",
    "titolo_album": "Layla and Other Assorted Love Songs",
    "genere": "Blues Rock",
    "anno_uscita_originale": 1970,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Polydor / Atco",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Layla_And_Other_Assorted_Love_Songs.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 65,
    "artista": "Tame Impala",
    "titolo_album": "The Slow Rush",
    "genere": "Psychedelic Pop",
    "anno_uscita_originale": 2020,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Modular / Interscope",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/The_Slow_Rush.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 66,
    "artista": "Tame Impala",
    "titolo_album": "Deadbeat",
    "genere": "Electronic / Dub Techno",
    "anno_uscita_originale": "??",
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "??",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Deadbeat.jpeg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 67,
    "artista": "R.E.M.",
    "titolo_album": "Out of Time",
    "genere": "Alternative Rock",
    "anno_uscita_originale": 1991,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Warner Bros.",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Out_Of_Time.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 68,
    "artista": "Alice in Chains",
    "titolo_album": "Dirt",
    "genere": "Grunge / Alternative Metal",
    "anno_uscita_originale": 1992,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Columbia",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Dirt.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 69,
    "artista": "The Rolling Stones",
    "titolo_album": "GRRR!",
    "genere": "Rock / Rock & Roll",
    "anno_uscita_originale": 2012,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "ABKCO / Universal",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "Compilation",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Grrr!.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 70,
    "artista": "John Lennon",
    "titolo_album": "Mind Games",
    "genere": "Rock",
    "anno_uscita_originale": 1973,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Apple",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Mind_Games.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 71,
    "artista": "The Beatles",
    "titolo_album": "Abbey Road",
    "genere": "Rock / Psychedelic Rock",
    "anno_uscita_originale": 1969,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Apple",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Abbey_Road.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 72,
    "artista": "Pink Floyd",
    "titolo_album": "The Division Bell",
    "genere": "Progressive Rock",
    "anno_uscita_originale": 1994,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "EMI / Columbia",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "??",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/The_Division_Bell.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 73,
    "artista": "The Beatles",
    "titolo_album": "1967-1970 (The Blue Album)",
    "genere": "Rock / Pop Rock",
    "anno_uscita_originale": 1973,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Apple",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "2LP",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/The_Beatles_1967_1970.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 74,
    "artista": "The Beatles",
    "titolo_album": "Let It Be",
    "genere": "Rock",
    "anno_uscita_originale": 1970,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Apple",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Let_It_Be.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 75,
    "artista": "Oasis",
    "titolo_album": "Time Flies... 1994-2009",
    "genere": "Britpop",
    "anno_uscita_originale": 2010,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Big Brother",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "Compilation",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Time_Flies_1994_2009.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 76,
    "artista": "Foo Fighters",
    "titolo_album": "In Your Honor",
    "genere": "Alternative Rock",
    "anno_uscita_originale": 2005,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "RCA",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/In_Your_Honor.jpg",
    "tracce": [],
    "foto_album": []
  },
  {
    "id": 77,
    "artista": "Mötley Crüe",
    "titolo_album": "Dr. Feelgood",
    "genere": "Hard Rock / Glam Metal",
    "anno_uscita_originale": 1989,
    "anno_stampa": "??",
    "anno_uscita_stampa": "??",
    "origine": "??",
    "etichetta": "Elektra",
    "catalog_number": "??",
    "codice_matrice": "??",
    "velocita": "33",
    "colore": "Nero",
    "grammatura": "??",
    "inserti": "??",
    "stato_disco": "??",
    "stato_copertina": "??",
    "note_stato": "",
    "stato_catalogo": "Wishlist",
    "cover": "Img/Dr_Feelgood.jpg",
    "tracce": [],
    "foto_album": []
  }
]
